update redis cache
RingsNetwork/rings-node pull request #167
Opened 2022-06-06 18:28 UTC by Raytlty

2022-06-07 07:57 UTC, RyanKung commented on rings-core/src/storage/cache.rs
> +use crate::err::{Error, Result};
1. I think it is *not* cache, it is persistence/semi-persistence storage, maybe the path should be `storage/persistence`
2. `RedisStorage` is only for Native build, it should be flagged as `#[cfg(not(features==`wasm`))`

2022-06-07 07:58 UTC, RyanKung commented on rings-core/src/storage/cache.rs
> +            let _ = parsed.set_password(Some("bns-redis-cache"));
r/bns/rings

2022-06-07 08:02 UTC, RyanKung commented on rings-core/src/storage/cache.rs
> +
We need a method to reduce storage size.

2022-06-08 05:08 UTC, googolmo commented on rings-core/src/storage/cache.rs
> +    fn current_size(&self) -> Result<Option<u64>> {
This function could NOT be used outside, Because the type of `K` is not known.

2022-06-15 07:27 UTC, googolmo commented on rings-core/Cargo.toml
> +redis = { version = "0.21" }
These two dependencies should set  `optional = true`, and only for default feature.

2022-06-15 07:27 UTC, googolmo commented on Cargo.toml
> +tempfile = { version = "3.2", optional = true }
These two dependencies can be removed.

2022-06-16 05:11 UTC, RyanKung requested changes
Redis support should be providing as a feature.
```
#[cfg(features = "redis")]
```

2022-06-16 05:11 UTC, googolmo commented on rings-core/src/storage/mod.rs
> +#[cfg(feature = "default")]
I think maybe use `#[cfg(not(feature = "wasm"))]` is better.

2022-06-16 05:11 UTC, googolmo commented on rings-core/src/storage/persistence/redis.rs
> +#[cfg(not(features = "wasm"))]
Maybe this line can be removed.

2022-08-08 16:02 UTC, closed without merging