Features/warmup with documents
RingsNetwork/rings-node pull request #311
Opened 2022-11-01 12:29 UTC by Raytlty

1. remove eip712 signer because this is PersonSign kind sign.
2. remove `sha1` crate and use `rust-crypto` instead. [reason](https://sha-mbles.github.io/)
3. simple doc without doctest

2022-11-02 04:21 UTC, googolmo requested changes

2022-11-02 04:21 UTC, googolmo commented on rings-core/src/prelude.rs
> +//! Re-exports of important traits, types, and functions used with rin-core.
Typo rings–core

2022-11-02 05:02 UTC, RyanKung commented on rings-core/src/ecc/signers.rs
> +pub mod person_sign {
rename to EIP191

2022-11-02 05:02 UTC, RyanKung commented on rings-core/src/ecc/signers.rs
> +pub mod person_sign {
ref: https://eips.ethereum.org/EIPS/eip-191

2022-11-02 05:03 UTC, RyanKung commented on rings-core/src/ecc/signers.rs
> -    fn test_eip712_sign() {
we should keep both `test_eip712_*`, and `test_eip191_*`

2022-11-02 05:15 UTC, RyanKung commented
As I understand, the original EIP712 is EIP191, and the current person_sign method is actually EIP191.
So, should we support SIGN as EIP712? Or EIP191 is good enough?

2022-11-02 05:18 UTC, RyanKung commented on rings-core/src/message/handlers/custom.rs
> +    ///
？

2022-11-02 05:22 UTC, RyanKung commented on rings-core/src/message/types.rs
> +/// MessageType use to ask for connection, send to remote with transport_uuid and handshake_info.
Coding style

```rust
/// Comment
#[derive]
pub struct foo {
}
```

2022-11-03 06:40 UTC, RyanKung approved these changes

2022-11-03 07:23 UTC, googolmo approved these changes

2022-11-03 07:24 UTC, merged