[WIP] New stablization algorithm for Correctness of DHT
RingsNetwork/rings-node pull request #392
Opened 2023-04-04 11:26 UTC by RyanKung

FACT

Related Issue: https://github.com/RingsNetwork/rings-node/issues/388

2023-04-18 12:07 UTC, Ma233 requested changes

2023-04-18 12:07 UTC, Ma233 commented on core/src/message/payload.rs
> +/// Encode with gzip
Please add comment in another pull request. (With enhanced grammar...)

2023-04-18 13:21 UTC, RyanKung commented on core/src/message/payload.rs
> +/// Encode with gzip
Code commenting should be done as byproduct. We have a lot of codes needs to be comment, thus If we wait a pull request for them, we will never do it.

2023-04-19 03:53 UTC, Ma233 approved these changes

2023-04-19 04:00 UTC, merged